#!/bin/sh -eu

# Update tiles.

# - use borders from brd/*.gpx
# - for each border render files which are touching the border
# - skip files if they are older then tile.list, older then the border
#   file, and no --all option is given.
# - render with --add switch: add information to existing tiles
# - render with --tmap_scale 1: rescale larger tiles to smaller ones.
# - do separately for zoom 9..12 and 0..8

MS2MAPDB=ms2mapdb
MS2NOM=ms2nom
tlist=TILES/tile.list
vmap_cnf=conf/import_vmap.cfg

mkdir -p TILES

all=0
if [ "${1:-}" = "--all" ]; then
  shift
  all=1
fi

need_upd=0
files=${@:-vmap/*.vmap}

# reset tiles mapdb
mapdb=mapdb/allmap/
rm -rf $mapdb
mkdir -p $mapdb
$MS2MAPDB create $mapdb

# For each border file
for brd_file in brd/*.gpx; do
  [ -f "$brd_file" ] || continue
    echo "Border: $brd_file"

  # For each map file
  for vmap in $files; do
    [ -f "$vmap" ] || continue
    name=$(basename $vmap .vmap)
    nom=$(./map_get_nom $name)

    # Is the file touches the border?
    $($MS2NOM --ext --name "$nom" --cover "$brd_file") || continue

    echo "Add map to index: $name"
    $MS2MAPDB import_vmap $mapdb $vmap --config "$vmap_cnf"

  done

  $MS2MAPDB render $mapdb --config conf/render.cfg\
    --define "{\"nom_name\":\"n37-025\", \"hr\":\"0\", \"border_style\":\"noclip\"}"\
    --tmap --add --out "TILES/{z}/{x}-{y}.png" --zmin 7 --zmax 14\
    --bgcolor 0 --png_format argb \
    --border_file $brd_file\
    --tmap_scale 1 --fit_patt_size;\

  $MS2MAPDB render $mapdb --config conf/render.cfg\
    --define "{\"nom_name\":\"n37-025\", \"hr\":\"0\", \"border_style\":\"none\"}"\
    --tmap --add --out "TILES/{z}/{x}-{y}.png" --zmin 0 --zmax 6\
    --bgcolor 0 --png_format argb \
    --border_file $brd_file\
    --tmap_scale 1 --mapdb_minsc 1;\
done
