#!/bin/sh -eu

# Make preview images.

MS2MAPDB=ms2mapdb
cmap=conf/cmap.png
vmap_cnf=conf/import_vmap.cfg
rend_cnf=conf/render.cfg

files=${@:-vmap/*.vmap}

# For each map file
for vmap in $files; do

  name="$(basename $vmap .vmap)"
  vmap="vmap/$name.vmap"
  [ -f "$vmap" ] || continue

  nom=$(./map_get_nom $name)
  png="OUT/$name.png"
  map="OUT/$name.map"
  new="diff/${name}_n.png"
  old="diff/${name}_o.png"
  dif="diff/${name}_d.png"
  mapdb="mapdb/tmp"

  # If git status is clean skip this file and delete
  # all pictures in diff folder
  st="$(git status --porcelain -- "$vmap")"
  if [ "$st" = "" ]; then
    rm -f diff/${name}_*.png
    continue
  fi

  # skip file if $new is newer then vmap
  [ "$vmap" -nt "$new" ] || continue

  # If there is $new file, move it to $old,
  # if not, generate it from last commit
  if [ -s "$new" ]; then
    mv -f "$new" "$old"
  else
    o_vmap="diff/tmp.vmap"
    git show "HEAD:$vmap" > "$o_vmap"
    $MS2MAPDB delete $mapdb
    $MS2MAPDB create $mapdb
    $MS2MAPDB import_vmap $mapdb $o_vmap --config "$vmap_cnf"

    $MS2MAPDB render $mapdb --out "$old" --config $rend_cnf\
      --define "{\"nom_name\":\"$nom\", \"hr\":\"1\"}"\
      --mkref nom --north --name $nom --dpi 150 --margins 10 --top_margin 30\
      --title "$name   /$(date +"%Y-%m-%d")/" --title_size 20\
      --cmap_load $cmap --png_format pal
    rm -rf $mapdb $o_vmap
  fi


  $MS2MAPDB delete $mapdb
  $MS2MAPDB create $mapdb
  $MS2MAPDB import_vmap $mapdb $vmap --config "$vmap_cnf"
  $MS2MAPDB render $mapdb --out "$new" --config $rend_cnf\
    --define "{\"nom_name\":\"$nom\", \"hr\":\"1\"}"\
    --mkref nom --north --name $nom --dpi 150 --margins 10 --top_margin 30\
    --title "$name   /$(date +"%Y-%m-%d")/" --title_size 20\
    --cmap_load $cmap --png_format pal
  rm -rf $mapdb

  [ -s "$old" -a -s "$new" ] && compare -matte "$old" "$new" "PNG8:$dif" ||:
done

