#!/bin/sh -efu

# Convert map filename to nomenclature name.
# In the simple case case: vmap/k44-060.vmap -> k44-060
# If fist parameter is --old then use mapsoft1 names.
#
# Usage:
#   map_get_nom [--old] <filename> <suffix>

old=0
if [ "$1" = "--old" ]; then
  shift
  old=1
fi

nom=$(basename $1 ${2:-})

# There was a file maps.txt co convert non-standard names.
# There are no such names now. It could be possible to
# do some conversions here.

# Convert name to mapsoft1 style.
if [ "$old" = 1 ]; then
  # Mapsoft1 uses "-" instead of "," for double sheets:
  nom=$(echo $nom | sed 's/,/-/')
fi

echo $nom
