#!/bin/sh -eu

# script used to rearrange git history using vmap_fix_diff

print_comm_files(){
  local commit="$1"
  git show --stat --format=format:"" "$commit" |
    sed -n 's|^[[:space:]]*\([^[:space:]]*.vmap\).*|\1|p'
}
print_comm_name(){
  local commit="$1"
  git log -1 --format=format:"%s" "$commit"
}


repo_in="/home/sla/MYMAP3/_podm/vmap"
repo_out="/home/sla/MYMAP3/_podm/vmap/n"

#repo_in="."
#repo_out="."

tac hist |
while read commit name; do

  cd "$repo_in"

#  name="$(print_comm_name "$commit")"

  echo "$commit $name"
  for f in $(print_comm_files "$commit"); do
    old="${f%.vmap}.bak.vmap"
    echo "$f"
    [ -f "$repo_out/$f" ] &&
      mv -- "$repo_out/$f" "$repo_out/$old" ||:
    git cat-file blob "$commit:$f" > "$repo_out/$f"
    [ -f "$repo_out/$old" ] &&
      vmap_fix_diff "$repo_out/$old" "$repo_out/$f" "$repo_out/$f" ||:
    rm -f -- "$repo_out/$old"
  done

  cd "$repo_out"
  git add *.vmap
  git commit -m "$name"
done
