#!/bin/sh -eu

# For a given region name (kav, zab, ...) get list of map names
#
# usage: get_map_list <name> <vmap_dir> <format>
#
# name can contain "all_" prefix, any folders and extensions.

reg=$1
mapdir=${2:-../vmap}

# Remove folders, extensions and all_ prefix
reg=${reg##*/}
reg=${reg%%.*}
reg=${reg#all_}

# Range in Pulkovo coords
case "$reg" in
  kav) range="[ 8080, 4685, 420, 210]" ;;
  fan) range="[12360, 4240, 320, 200]" ;;
  pam) range="[13180, 4050, 250, 350]" ;;
  tsh) range="[14240, 4610, 150, 130]" ;;
  zab) range="[19310, 6020, 420, 320]" ;;
  saj) range="[17260, 5560, 390, 480]" ;;
  nep) range="[14240, 3120, 700, 350]" ;;
  put) range="[16415, 7615,  90, 160]" ;;
  ura) range="[10580, 7160, 120, 100]" ;;
  sun) range="[24380, 6835, 300, 200]" ;;
  chi) range="[48650,-4980, 180, 280]" ;;
  podm) range="[7085, 5970, 600, 400]" ;;
  *) echo "Unknown region: $reg" 1>&2; exit 1;;
esac

# Convert to wgs
range_wgs="$(ms2proj --from SU --scale 1000 "$range")"


# Find all nomenclature-based map names
for n in $(ms2nom -E -r "$range_wgs" -s 100k); do
  for n1 in $(echo $mapdir/$n*.vmap); do
    [ -f "$n1" ] || continue
    echo $n1
  done
done
