#!/bin/sh -efu

# make HTML index for multiple maps
# usage:
#   make_html_index <name> <html_area> <odir>

name=$1
area=${2:-}
odir=${3:-OUT}
vdir=${4:-vmap}

txt="$odir/all_$name.txt"

## HTML header
cat <<EOF
<html>
<head>
  <title>$name</title>
  <META HTTP-EQUIV="Content-Type" CONTENT="text/html; charset=koi8-r">
</head>
<body>
EOF

## Map-specific text file
[ ! -f "$txt" ] || cat "$txt"

## Area (produced by mapsoft)
[ ! -f "$area" ] || sed -e '
  /^<area/ {
    s/"\([^"]*\)\.jpg"/"\1.htm"/
  }
  s|'$odir'/||g
  /<\/html>/d
  /<html>/d
' "$area"

# List of map names
if [ -f "$area" ]; then
  names="$(sed -n -r -e '/^<area/ { s/.* href=\"[^\"]*\/([^\"/]+).jpg\".*/\1/p}' "$area")"
  echo "<ul>"
  for n in $names; do
    ## modification time of html
    #d="$(stat -c %Z "$odir/$n.htm")"
    #d="$(date -d @$d +%Y-%m-%d)"

    ## last commit in vmap
    d="$(git log -1 --pretty="format:%ci" "$vdir/$n.vmap" | cut -d ' ' -f 1)"
    echo "<li><b>$n</b> (<font color=gray>$d</font>): "
    echo "  <a href=\"$n.png\">[PNG]</a>"
    echo "  <a href=\"$n.map\">[MAP]</a>"
    echo "  <a href=\"$n.mp.zip\">[MP.ZIP]</a>"
    echo "  <a href=\"$n.img\">[IMG]</a>"
  done
  echo "</ul>"
fi

## tail
cat <<EOF
  </ul>
  <p><a href="all_$name.img">Полная карта для Garmin, IMG</a>
  <p><a href="https://github.com/slazav/map_hr">
      Исходники карт на github (самодельный векторный формат)</a>
  <p>Замечания и дополнения принимаются по адресу slazav at altlinux.org.
  <p>Последнее обновление: $(date +"%F %X")
</body>
</html>
EOF
